### ISSUE TITLE
No keyboard input

### ISSUE THREAD

**Issue by AlvaroPata** [ranelpadon/ngram-type#10]
Hi! I was trying to practice with the website, but the keyboard input is not being recognised. Also, I think the white bar is covering text (see the screenshot)...

<img width="1278" alt="Screenshot 2022-01-25 at 16 27 00" src="https://user-images.githubusercontent.com/69887666/151006905-03e5ad22-906d-4996-b7a2-1ba685eabeaf.png">

**Comment by ranelpadon** [comment]
I tried it now and works fine:
https://ranelpadon.github.io/ngram-type/

<img width="1440" alt="Screen Shot 2022-01-26 at 1 22 14 AM" src="https://user-images.githubusercontent.com/4292088/151027271-59ba75e6-cea0-45b9-b5b8-d14bf362bb88.png">

Have you tried clicking the text field by a mouse, then type something? And could you navigate the fields/sections using `TAB` key?
> but the keyboard input is not being recognised

Not clear what you meant here:
> Also, I think the white bar is covering text (see the screenshot)...

Also, please specify your:
- OS
- device (laptop, iPad, PC, etc)
- browser
- keyboard (built-in like in laptop, or external device)
- layout (Colemak, Dvorak, etc)

**Comment by ranelpadon** [comment]
@AlvaroPata closing this issue since you didn't give further details/feedback. Likewise, I don't think there's input issue on the site, since lots of users are still using it. Let me know if you think otherwise. Thanks

**Comment by AlvaroPata** [comment]
Hi! I’m using Firefox on MacOS.

**Comment by ranelpadon** [comment]
Interesting, I'm using Firefox latest version (**97.0.2**) on Mac Mojave (10.14), and it looks ok:

<img width="1440" alt="Screen Shot 2022-03-07 at 6 36 38 PM" src="https://user-images.githubusercontent.com/4292088/157015348-a09713ea-2954-4445-8f24-415d48ad2e6e.png">

May I know your Firefox and MacOS versions?

**Comment by AlvaroPata** [comment]
I’m on Monterrey.
OS: macOS 12.2.1 21D62 x86_64
Firefox: 97.0.2 (64-bit)

And it looks like this:

**Comment by ranelpadon** [comment]
@AlvaroPata Thanks, what is your monitor size? Are you using MacBook, iMac, or via external monitor?

**Comment by AlvaroPata** [comment]
I'm on a MacBook Air. Not sure about the behaviour on an external monitor, I can check it when I get the chance and tell you.

**Comment by ranelpadon** [comment]
@AlvaroPata I think I figured it out, you're using **MacBook Air** which I think has a smaller screen than my **15" MacBook Pro**, right? 

I could simulate the issue when I **reduce** the browser size (this is similar to the issue of my friend, and worse than yours I think):

<img width="1188" alt="Screen Shot 2022-03-07 at 7 05 43 PM" src="https://user-images.githubusercontent.com/4292088/157019869-6a23bd35-26e0-46f6-9fa0-4363ef5dfb0d.png">

**Comment by ranelpadon** [comment]
Also, a workaround for now is to **zoom out** the page to compensate for the smaller viewport. Could you please try it? Just hit the zoom-out shortcut once or twice, or until the typing input field looks ok:

<img width="153" alt="Screen Shot 2022-03-07 at 7 11 33 PM" src="https://user-images.githubusercontent.com/4292088/157020505-8bc2d33a-0ca4-4c4f-a7a4-3872ae62906c.png">

**Comment by AlvaroPata** [comment]
Hi @ranelpadon, your suggested workaround works. I set the zoom to 90% and everything works as expected! Thanks for looking into it!
<img width="1280" alt="Screenshot 2022-03-07 at 15 20 58" src="https://user-images.githubusercontent.com/69887666/157051831-6f96aecd-8b9f-4523-aa05-5fc6057e0cf1.png">

**Comment by ranelpadon** [comment]
@AlvaroPata Nice, glad to hear that! Thanks also for your cooperation. I still need to fix that, so that the user doesn't need to zoom out when using smaller screens, via responsive CSS. Probably, this weekend. Cheers :)

**Comment by ranelpadon** [comment]
@AlvaroPata I pushed a fix for it now and other style improvements. Please check again once you have the chance. You may need to clear your browser cache if it's still not being reflected. Looks better now on my end, and should handle even those smaller/zoomed-in screens. So, it should work even in your default zoom level:
https://ranelpadon.github.io/ngram-type/

Let me know if it's indeed a fix also on your end, so that we could close this. :)
