### ISSUE TITLE
Test doesn't end immediately after typing last character

### ISSUE THREAD

**Issue by xsrvmy** [ranelpadon/ngram-type#12]
There is a delay between typing the last character and advancing to the next test. If you type a space during this time (which is kinda natural) it causes an error instead and the test also fails to advance.

**Comment by ranelpadon** [comment]
Ok will take a look asap and try to replicate. Thanks

**Comment by ranelpadon** [comment]
@xsrvmy Sorry for the delay. Fixed as per https://github.com/ranelpadon/ngram-type/commit/264320652370041907a0a44f88b04f3f582f6c74. You might want to clear your browser cache first just to make sure. Thanks

**Comment by ranelpadon** [comment]
FYI, closing this since I believe this is already fixed. Feel free to re-open if you still have issues. Thanks
