### ISSUE TITLE
cyrillic support

### ISSUE THREAD

**Issue by nicholay-i** [ranelpadon/ngram-type#20]
cyrillic symbols support would be really helpfull

**Comment by ranelpadon** [comment]
Do you mean to support translations? Someone ported it into Russian before:
https://aleuxser.github.io/ngram-type-ru/

The main target of Ngram Type is the English language though. Each language has a different set of Top 50 or Top 100 Ngrams, hence automated translations are not feasible, and need a manual compilation of the Ngrams for each language. 

You could use the `Custom` feature though in the **Source** section if you want some custom texts/ngrams for practice, especially for other languages/characters:

<img width="1726" alt="Screenshot 2023-01-01 at 6 59 33 AM" src="https://user-images.githubusercontent.com/4292088/210157096-07418ba1-6075-4118-b8cd-0730e2ee154e.png">

**Comment by nicholay-i** [comment]
Wow, that's exactly wat I was looking for. Thanks!
