### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ooloth** [ranelpadon/ngram-type#3]
I discovered this tool via [this YouTube video](https://youtu.be/sI-a64EVPPU) and I'm finding it really helpful as I learn Colemak DH.

Just wanted to say thanks. :)

**Comment by ranelpadon** [comment]
@ooloth Wow, thanks a lot for informing me about this video! I watched it and its content is interesting and delightful indeed. I have another project as well for familiarizing the Colemak/Colemak DH keys, which you might be interested also:
https://ranelpadon.github.io/keyzen-colemak-dh/

And make sure to join the vibrant and friendly Colemak Discord server/community. Really appreciate your extra effort. :)
